PLAT-100: Mamda subscription deactivation failure (#171)
Calling MamdaSubscription.deactivate() in C# was not working properly resulting in the following issue:

Could not deallocate mamaSubscription as it has not been destroyed.
Wombat.MamaException: mamaStatus: (MAMA_STATUS_SUBSCRIPTION_INVALID_STATE)

JAVA was also updated to reflect this change (however the same issue didnt not exist in JAVA)

Signed-off-by: Gary Molloy <g.molloy@srtechlabs.com>