MAMDA: Remove unnamed typedef from bookpulisher example.
Fixing a simple compiler warning with the bookpublisher application,
where the order struct is preceeded by an unnecessary typedef.

When built with clang and our compiler flags, this actually triggers
an error:

mamda/c_cpp/src/examples/orderbooks/bookpublisher.cpp:119:1: error:
    typedef requires a name [-Werror,-Wmissing-decl    arations]
    typedef struct order

Removing the typedef resolves the problem.

Signed-off by: Damian Maguire <dmaguire@nyx.com>