[MAMA] Remove extra parens on comparison.
Building OpenMAMA with modern releases of Clang suffers from
issues with the NOMEM_STATUS_CHECK macro, specifically with -Werror.
This results in the following build failure:

clang -o objdir/mama/c_cpp/src/c/payload/qpidmsg/payload.o [...]
WARNING:: mama/c_cpp/src/c/payload/qpidmsg/payload.c:4108:19:
error: equality comparison with extraneous parentheses [-Werror,-Wparentheses-equality]
    do { if ((impl==((void*)0))) { mama_log (MAMA_LOG_LEVEL_SEVERE, [...]
                  ~~~~^~~~~~~~~~~~
                  mama/c_cpp/src/c/payload/qpidmsg/payload.c:4108:19:
note: remove extraneous parentheses around the comparison to silence this warning

The issue here is that in order to avoid programming errors with
comparisons v assignments within if statements, the compiler expects
an explicit notation within the code to demonstrate that you know
what you're doing - extra-parens for assignments, single parens
for comparions.

The fix is simple - remove the extraneous parentheses.

Signed-off by: Damian Maguire <damian.j.maguire@gmail.com>