[COMMON] Fixing compiler error with wUuid_clear
New warning triggered by recent versions of clang relating to unused
result.

WARNING::mama/c_cpp/src/c/bridge/qpid/inbox.c:194:30: error: expression result
unused [-Werror,-Wunused-value]
    wUuid_clear             (tempUuid);

Cleaning up the define resolves this issue.

Signed-off by: Damian Maguire <damian.j.maguire@gmail.com>